@startuml
start

:Получение запроса POST /api/v1/register;

:Проверка наличия всех полей
(firstName, lastName, username, password, captchaToken);

if (Все поля заполнены?) then (Нет)
  :Вернуть 400 Bad Request
  "All fields are required.";
  stop
else (Да)
endif

:Валидация firstName (буквы, длина ≤ 50);
if (Валидно?) then (Нет)
  :Вернуть 400 Bad Request
  "Invalid first name";
  stop
else (Да)
endif

:Валидация lastName (буквы, длина ≤ 50);
if (Валидно?) then (Нет)
  :Вернуть 400 Bad Request
  "Invalid last name";
  stop
else (Да)
endif

:Валидация username (3-30 символов, латиница/цифры/_);
if (Валидно?) then (Нет)
  :Вернуть 400 Bad Request
  "Invalid username";
  stop
else (Да)
endif

:Валидация password (8+ символов,
цифра, заглавная, строчная, спецсимвол);
if (Валидно?) then (Нет)
  :Вернуть 400 Bad Request
  "Password requirements...";
  stop
else (Да)
endif

:Проверка reCAPTCHA через Google API;
if (reCAPTCHA валидна?) then (Нет)
  :Вернуть 400 Bad Request
  "Please verify reCaptcha to register!";
  stop
else (Да)
endif

:Проверка уникальности username в БД;
if (Username уже существует?) then (Да)
  :Вернуть 409 Conflict
  "User exists!";
  stop
else (Нет)
endif

:Хеширование пароля (bcrypt);

:Сохранение пользователя в БД;

:Генерация ответа 201 Created
с userId, username, message, redirectUrl;

stop
@enduml
